### PR TITLE
Presentation

### PR DESCRIPTION
**Pull request by RBirkeland**
In the case the mentors would like to overview our progress on what is happening outside of github (google docs) :)

### CODE REVIEW

**Comment by pfent** [comment]
Please use Gitter / other channels for such communications regarding presentations. Issues are project related things only please.

**Comment by kordianbruck** [comment]
@RBirkeland you can always open a separate Repository and mail me the address. I might check in ;)

**Comment by pfent** [comment]
or just follow the [link](https://docs.google.com/presentation/d/1HBV6MB8C0kraLEJwc8o8-EeXGkJSayuZFBW9HhXt_8Y/edit) to the google doc, because that's where the action happens ;-)

**Comment by kordianbruck** [comment]
@pfent pssst - I like emails

**Pull request closed without merging**
