### PR TITLE
Update nodejs version in Dockerfile

### LINKED ISSUE #16: Dockerfile improvements
Please update https://github.com/MusicConnectionMachine/RelationshipsG3/blob/develop/Dockerfile#L1 to `boron`

### PR DESCRIPTION
**Pull request by Henni**
fixes #16 

@ansjin you set this up. Please do a short review.

### CODE REVIEW

**Comment by sacdallago** [comment]
@Henni next time you can commit with a message such as `"closes #16"` so when the commit get's merged in develop (after the PR is approved, in other words), #16 will close automatically!
https://help.github.com/articles/closing-issues-via-commit-messages/

The power of GH.

**Comment by Henni** [comment]
@sacdallago also works with the "fixes #16 " I added in the PR description.

**Comment by sacdallago** [comment]
@Henni seriously? Cool :D Didn't know that

**Review by ansjin — APPROVED** [review]
Correct!

**Pull request merged**
